name: PDF Generator

# Controls when the action will run. Triggers the workflow on push or pull request
# events
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
   pull_request:
    branches: [ master ]
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pandoc_convert:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name : set up git repository
        uses: actions/checkout@v1
      # PDF
      - name: build latex
        uses: xu-cheng/latex-action@v2
        with:
            # The root LaTeX file to be compiled
            root_file: paper.tex
      - name: store output
        uses: actions/upload-artifact@main
        with:
          name: paper.pdf
          path: paper.pdf
          retention-days: 7
#     # Dropbox upload: Needs a repository secret set to work.
#     - name: dropbox upload
#       uses: deka0106/upload-to-dropbox@v2
#       with:
#         dropbox_access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
#         src: paper.pdf
#         dest: /paper.pdf
#         mode: overwrite
